//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkLib.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>Project type</summary>
    public partial class Project : Entity<Project>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Project"/> class.
        /// </summary>
        /// <param name="data">The data.</param>
        public Project(object data = null) : base(data)
        { }
        /// <summary>Initializes a new instance of the <see cref="Project" /> class.</summary>
        public Project()
        {
            this.Users = new HashSet<User>();
        }

        /// <summary>Gets or sets the project identifier.</summary>
        /// <value>The project identifier.</value>
        [Key]
        public int ProjectId { get; set; }
        /// <summary>Gets or sets the name of the project.</summary>
        /// <value>The name of the project.</value>
        [Required(ErrorMessage = "Project name is required.")]
        public string ProjectName { get; set; }
        /// <summary>Gets or sets the project description.</summary>
        /// <value>The project description.</value>
        public string ProjectDescription { get; set; }

        /// <summary>Gets or sets the users for project.</summary>
        /// <value>The users.</value>
        public ICollection<User> Users { get; set; }
    }
}
