//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkLib.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using WorkLib.Data;

    /// <summary>Project type</summary>
    public partial class Project : Entity<Project>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Project"/> class.
        /// </summary>
        /// <param name="data">The data.</param>
        public Project(object data = null) : base(data)
        { }

        /// <summary>Gets or sets the project identifier.</summary>
        /// <value>The project identifier.</value>
        [Key]
        [Display(Name = "Id")]
        public int ProjectId { get; set; }
        /// <summary>Gets or sets the name of the project.</summary>
        /// <value>The name of the project.</value>
        [Required(ErrorMessage = "Project name is required.")]
        [Display(Name = "Name")]
        public string ProjectName { get; set; }
        /// <summary>Gets or sets the project description.</summary>
        /// <value>The project description.</value>
        [Display(Name = "Description")]
        public string ProjectDescription { get; set; }

        public override void Delete(DbContext context = null)
        {
            throw new NotImplementedException();
        }

        public override void Save(DbContext context = null)
        {
            throw new NotImplementedException();
        }
    }
}
